In [1]:
from time import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from alarm_framework.alarm_generator.alarm_generator import*
from alarm_framework.alarm_tunnig.sig3 import*

In [2]:
proc_var = pd.read_csv("proc_dist_2_aval.csv", index_col='tout')
proc_var.index = pd.to_datetime(proc_var.index, unit='s')
alarm_settings = sigma3_threshold(proc_var, ['xmeas01'])
alarm_settings[1].on_delay = 0.00
alarm_settings[1].off_delay = 0.00
alarm_data = alarm_seq(proc_var, [alarm_settings[1]])
log_alarm = alarm_log(alarm_data)

/home/emerson/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:466: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
proc_var.head()

,xmeas01,xmeas02,xmeas03,xmeas04,xmeas05,xmeas06,xmeas07,xmeas08,xmeas09,xmeas10,...,xmeas13,xmeas14,xmeas15,xmeas16,xmeas17,xmeas18,xmeas19,xmeas20,xmeas21,xmeas22
tout,,,,,,,,,,,,,,,,,,,,,
2018-03-31 11:27:07.125310,0.271033,3649.739415,4451.320791,9.223142,32.392900,47.559754,2798.975799,64.995825,122.898796,0.197826,...,2703.521071,25.257559,49.681867,3330.810326,22.886207,66.628303,0.000000,272.782177,102.480028,92.262531
2018-03-31 11:27:43.125310,0.270093,3663.351750,4428.605105,9.277658,32.563969,47.917222,2799.059838,65.254940,122.883398,0.195161,...,2704.210572,25.229661,51.910601,3331.086587,22.851612,66.625463,0.369217,272.375911,102.484819,92.331837
2018-03-31 11:28:19.125310,0.271255,3656.090868,4429.093949,9.280946,32.098618,47.750928,2799.345791,64.930642,122.909663,0.198072,...,2703.786423,25.406979,50.032222,3330.554344,23.119233,66.630030,-0.771111,272.901051,102.499473,92.251275
2018-03-31 11:28:55.125310,0.269950,3664.897833,4439.129238,9.252639,32.611594,47.305023,2799.251300,65.188788,122.909316,0.196598,...,2703.841194,25.327830,48.555982,3330.739111,23.071501,66.640923,-1.206464,272.678676,102.465085,92.212726
2018-03-31 11:29:31.125310,0.270947,3616.540495,4446.078748,9.256099,32.311441,47.813862,2798.967112,65.686033,122.887484,0.197137,...,2702.960633,25.406375,50.666658,3330.837786,23.106484,66.622834,0.150893,272.680510,102.463271,92.205306

In [22]:
def add(proc_var,log_alarm):
    ts = 0
    td__ = []
    for i in np.arange(0,10):
        td = []
        for i in np.arange(0,10):
            t0 = proc_var['xmeas01'].index[ts + 4000]
            for i in np.arange(0,len(log_alarm)):
                if log_alarm.index[i] >= t0 and log_alarm.iloc[i]['STATE'] == 'ALM':
                    td.append(log_alarm.index[i] - t0)
                    break
            ts = ts + 10000
        td_ = np.array(td)
        td__.append(td_.mean())
    
    Td = np.array(td__)
    mTd = Td.mean()
    #sTd = Td.std()
    return mTd

In [23]:
add(proc_var,log_alarm)

Timedelta('1 days 10:01:19.200000')